name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: criterion
      run: sudo apt-get install libcriterion-dev valgrind -y
    - name: make
      run: make
    - name: make test
      run: make test
    - name: leak
      run make leak
